/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc_robot_JniInterface */

#ifndef _Included_frc_robot_JniInterface
#define _Included_frc_robot_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frc_robot_JniInterface
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_JniInterface_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
